/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        geist: ['geist-regular', 'system-ui', '-apple-system', 'sans-serif'],
        'geist-regular': ['geist-regular', 'system-ui', '-apple-system', 'sans-serif'],
        'geist-thin': ['geist-thin', 'system-ui', '-apple-system', 'sans-serif'],
        'geist-extralight': ['geist-extralight', 'system-ui', '-apple-system', 'sans-serif'],
        'geist-light': ['geist-light', 'system-ui', '-apple-system', 'sans-serif'],
        'geist-medium': ['geist-medium', 'system-ui', '-apple-system', 'sans-serif'],
        'geist-semibold': ['geist-semibold', 'system-ui', '-apple-system', 'sans-serif'],
        'geist-bold': ['geist-bold', 'system-ui', '-apple-system', 'sans-serif'],
        'geist-extrabold': ['geist-extrabold', 'system-ui', '-apple-system', 'sans-serif'],
        'geist-black': ['geist-black', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        'default-primary': '#3B82F6',
        'default-success': '#2CBE00',
        'default-black': '#171717',
        'app-bg-secondary': '#1F2937',
        'app-bg-muted': '#A3A3A3',
        'default-green': '#2CBE00',
        'text-accent': '#3B82F6',
        'text-primary': '#FFFFFF',
        'text-secondary': '#BABABA',
        'text-muted': '#94A3B8',
        'text-placeholder': '#6B7280',
        'text-status-error': '#F87171',
        'card-bg': '#1E293B',
        'card-border': '#334155',
        'input-bg': '#334155',
        'icon-primary': '#FFFFFF',
        'icon-secondary': '#9CA3AF',
        'status-success': '#34D399',
        'status-warning': '#FBBF24',
        'status-error': '#F87171',
        'status-info': '#60A5FA',
      },
    },
  },
  plugins: [],
};
